In [16]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arange(6).reshape(2,3)
print("일차 다항식 계수 : ",X)




일차 다항식 계수 :  [[0 1 2]
 [3 4 5]]


In [17]:
poly = PolynomialFeatures(degree=2)
poly_ftr = poly.fit_transform(X)

print("변경된 2차 다항식 계수 : ",poly_ftr)

변경된 2차 다항식 계수 :  [[ 1.  0.  1.  2.  0.  0.  0.  1.  2.  4.]
 [ 1.  3.  4.  5.  9. 12. 15. 16. 20. 25.]]


In [22]:
# 파이프라인을 이용해서 3차 다항 회귀 실습
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

def polynomial_func(X):
    y = 1 + 2*X + X**2 + X**3
    return y

# Pipeline 객체로 Streamline하게 Polynomial Feature 변환과 Linear Regression을 연결
model = Pipeline([('poly',PolynomialFeatures(degree=3)),('linear',LinearRegression())])

X = np.arange(4).reshape(2,2)
y = polynomial_func(X)

model = model.fit(X,y)
print('Poltnomial 회귀계수:', np.round(model.named_steps['linear'].coef_,2))

Poltnomial 회귀계수: [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
